services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: haiku
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cloudbeaver:
    image: dbeaver/cloudbeaver
    restart: always
    environment:
      CB_SERVER_NAME: CB Server
      CB_ADMIN_NAME: cbeaver
      CB_ADMIN_PASSWORD: cbeaver
      CB_DB_DRIVER: postgresql
      CB_DB_URL: jdbc:postgresql://postgres:5432/haiku
      CB_DB_USER: admin
      CB_DB_PASSWORD: secret
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - postgres
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4470:8080"
    depends_on:
      - postgres
    environment:
      JWT_SECRET_KEY: haiku
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4471:3000"

volumes:
  postgres_data:
  cloudbeaver_data:
